#include<bits/stdc++.h>
using namespace std;
int main()
{
    char c;
    while((scanf("%c",&c))==1)
    {
        if(c=='=')
            cout<<"-";
        if(c=='-')
            cout<<"0";
        if(c=='0')
            cout<<"9";
        if(c=='9')
            cout<<"8";
        if(c=='8')
            cout<<"7";
        if(c=='7')
            cout<<"6";
        if(c=='6')
            cout<<"5";
        if(c=='5')
            cout<<"4";
        if(c=='4')
            cout<<"3";
        if(c=='3')
            cout<<"2";
        if(c=='2')
            cout<<"1";
        if(c=='1')
            cout<<"`";
        if(c=='\\')
            cout<<"]";
        if(c==']')
            cout<<"[";
        if(c=='[')
            cout<<"P";
        if(c=='P')
            cout<<"O";
        if(c=='O')
            cout<<"I";
        if(c=='I')
            cout<<"U";
        if(c=='U')
            cout<<"Y";
        if(c=='Y')
            cout<<"T";
        if(c=='T')
            cout<<"R";
        if(c=='R')
            cout<<"E";
        if(c=='E')
            cout<<"W";
        if(c=='W')
            cout<<"Q";
        if(c=='\'')
            cout<<";";
        if(c==';')
            cout<<"L";
        if(c=='L')
            cout<<"K";
        if(c=='K')
            cout<<"J";
        if(c=='J')
            cout<<"H";
        if(c=='H')
            cout<<"G";
        if(c=='G')
            cout<<"F";
        if(c=='F')
            cout<<"D";
        if(c=='D')
            cout<<"S";
        if(c=='S')
            cout<<"A";
        if(c=='/')
            cout<<".";
        if(c=='.')
            cout<<",";
        if(c==',')
            cout<<"M";
        if(c=='M')
            cout<<"N";
        if(c=='N')
            cout<<"B";
        if(c=='B')
            cout<<"V";
        if(c=='V')
            cout<<"C";
        if(c=='C')
            cout<<"X";
        if(c=='X')
            cout<<"Z";
        if(c==' ')
            cout<<" ";
        if(c=='\n')
            cout<<"\n";
    }
    return 0;
}
